#!/bin/bash

# All Packages include
packages=(
    "git"
    "vim"
    "htop"
    "neovim"
    "wget"
    "curl"
    "docker"
    "tmux"
    "gcc"
    "make"
    "python"
    "python-pip"
    "go"
    "hugo"
    "zsh"
    "firefox"
    "gimp"
    "vlc"
    "filezilla"
    "obs-studio"
    "discord"
    "slack"
    "gitkraken"
    "chromium"
    "calibre"
    "docker-compose"
    "p7zip"
    "rsync"
    "libreoffice-fresh"
    "texlive-most"
    "imagemagick"
    "audacity"
    "kdenlive"
    "mupdf"
    "networkmanager"
    "bash-completion"
    "postman-bin"
    "neofetch"
    "nano"
    "xorg"
    "xorg-xinit"
    "picom"
    "postgresql"
    "apache"
    "fastfetch"
    "mpv"
    "unzip"
    "feh"
    "lutris"
    "okular"
    "virt-manager"
    "handbrake"
    "kodi"
    "flameshot"
    "blender"
    "easyeffects"
    "libreoffice-fresh"
    "thunderbird"
    "darktable"
    "tlp"
    "redshift"
    "timeshift"
    "syncthing"
    "bleachbit"
    "onionshare"
    "drawio-desktop"
    "kitty"
    "vnstat"
    "hdparm"
    "mesa-utils"
    "networkmanager"
    "netctl"
    "xsel"
    "xclip"
    "xorg-server"
    "xorg-xrandr"
    "scrot"
    "bspwm"
    "sxhkd"
    "sway"
    "qtile"
    "i3-vm"
    "noto-fonts-emoji"
)

# 
sudo pacman -Syu

# Install packages
for package in "${packages[@]}"; do
    sudo pacman -S --noconfirm "$package"
done

echo "All packages installed."

